name: CI/CD Client Histudy

on:
  push:
    branches:
      - "main"
    paths:
      - "client/**"

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
  VUE_ENV: ${{ secrets.CLIENT_ENV }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Create .env file for Vue.js with CLIENT_ENV secrets
        run: |
          # Tạo file .env cho client từ CLIENT_ENV secrets
          echo "VUE_ENV=${{ env.VUE_ENV }}" > client/.env

      - name: Install dependencies and Build Vue.js application
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to EC2 with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          source: "client/dist/*"
          target: "/var/www/histudy"

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
