name: CI/CD CMS Histudy

on:
  push:
    branches:
      - "main"
    paths:
      - "cms/**"

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies and Build Vue.js application
        run: |
          cd cms
          npm install
          npm run build

      - name: Set up cms directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            if [ ! -d "/var/www/histudy" ]; then
              echo "Directory /var/www/histudy/cms does not exist. Creating it now."
              sudo mkdir -p /var/www/histudy/cms
            fi

            sudo chown -R ubuntu:ubuntu /var/www/histudy/cms
            sudo chmod -R 775 /var/www/histudy/cms

      - name: Deploy to EC2 with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          source: "cms/dist/*"
          target: "/var/www/histudy"

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
