name: CI/CD Server Histudy

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Ensure server directory exists
        run: mkdir -p ./server

      - name: Create .env file
        run: |
          echo "LARAVEL_ENV=${{ secrets.LARAVEL_ENV }}" > .env

      - name: Debug secret
        run: echo "LARAVEL_ENV=${{ secrets.LARAVEL_ENV }}"

      - name: Install Dependencies
        run: composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

      - name: Generate Laravel key
        run: php artisan key:generate --force

      - name: Set storage permissions
        run: |
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

      - name: Run migrate and optimize
        run: |
          php artisan migrate --force
          php artisan optimize

      - name: Start Laravel server
        run: |
          nohup php artisan serve --host=0.0.0.0 --port=8000 &
