name: CI/CD Server Histudy

on:
  push:
    branches:
      - "main"
    paths:
      - "server/**" # Chỉ deploy khi có thay đổi trong thư mục server

env:
  EC2_HOST: ${{ secrets.EC2_HOST }} # Địa chỉ IP hoặc tên miền EC2 của bạn
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }} # Tên người dùng EC2 (thường là ubuntu)
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }} # SSH private key để truy cập EC2
  LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }} # Môi trường Laravel (dev, prod...)

jobs:
  deploy:
    runs-on: ubuntu-latest # Dùng GitHub-hosted runner (ubuntu-latest)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Lấy mã nguồn từ repository

      - name: Deploy to EC2 with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOST }} # Địa chỉ host EC2
          username: ${{ env.EC2_USERNAME }} # Tên người dùng trên EC2
          key: ${{ env.EC2_PRIVATE_KEY }} # SSH private key để kết nối
          port: 22 # Cổng SSH mặc định
          source: "server/**" # Đường dẫn tới thư mục server trong repository
          target: "/var/www/histudy/server" # Đường dẫn đích trên EC2

      - name: Set up Laravel environment and run deployment tasks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            # Kiểm tra xem thư mục server có tồn tại không, nếu không thì tạo
            if [ ! -d "/var/www/histudy/server" ]; then
              echo "Directory /var/www/histudy/server does not exist. Creating it now."
              sudo mkdir -p /var/www/histudy/server
              sudo chown ubuntu:ubuntu /var/www/histudy/server
              sudo chmod -R 775 /var/www/histudy/server
            else
              echo "Directory /var/www/histudy/server already exists."
            fi

            # Tạo file .env và sao chép nội dung từ LARAVEL_ENV vào
            echo "LARAVEL_ENV=${{ env.LARAVEL_ENV }}" | sudo tee /var/www/histudy/server/.env

            # Di chuyển vào thư mục chứa server
            cd /var/www/histudy/server

            # Cài đặt dependencies cho Laravel
            sudo composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

            # Tạo key cho Laravel
            sudo php artisan key:generate --force

            # Chạy migrate và optimize
            sudo php artisan migrate --force
            sudo php artisan optimize

            # Cấp quyền cho thư mục storage và bootstrap/cache
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache
