jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Di chuyển thư mục code Laravel vào /var/www
            mv ~/histudy /var/www/histudy/server
            cd /var/www/histudy/server

            # Đảm bảo quyền truy cập thư mục
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache

            # Cài đặt dependencies
            export COMPOSER_ALLOW_SUPERUSER=1
            sudo composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

            # Tạo key cho Laravel
            sudo php artisan key:generate --force

            # Thực thi migration và tối ưu hóa
            sudo php artisan migrate --force
            sudo php artisan optimize

            # Khởi động lại Nginx nếu cần
            sudo systemctl restart nginx
          EOF
