name: CI/CD Server Histudy

on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
  LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Di chuyển thư mục code Laravel vào /var/www
            sudo mv ~/histudy/server /var/www/histudy
            cd /var/www/histudy

            # Cài đặt các dependencies
            sudo composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

            # Cài đặt quyền cho các thư mục cần thiết
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache

            # Tạo key cho Laravel
            sudo php artisan key:generate --force

            # Thực thi migration và tối ưu hóa
            sudo php artisan migrate --force
            sudo php artisan optimize
