- name: Set up Laravel environment and run deployment tasks
  uses: appleboy/ssh-action@master
  with:
    host: ${{ env.EC2_HOST }}
    username: ${{ env.EC2_USERNAME }}
    key: ${{ env.EC2_PRIVATE_KEY }}
    port: 22
    script: |
      echo "LARAVEL_ENV=${{ env.LARAVEL_ENV }}" | sudo tee /var/www/histudy/server/.env
      sudo chown www-data:www-data /var/www/histudy/server/.env
      sudo chmod 644 /var/www/histudy/server/.env

      if [ ! -d "/var/www/histudy/server/storage/app/firebase" ]; then
        echo "Firebase directory does not exist. Creating it now."
        sudo mkdir -p /var/www/histudy/server/storage/app/firebase
      fi

      echo "FIREBASE_ADMIN_SDK=${{ env.FIREBASE_ADMIN_SDK }}" | sudo tee /var/www/histudy/server/storage/app/firebase/histudy-2024-firebase-adminsdk.json
      sudo chown www-data:www-data /var/www/histudy/server/storage/app/firebase/histudy-2024-firebase-adminsdk.json
      sudo chmod 644 /var/www/histudy/server/storage/app/firebase/histudy-2024-firebase-adminsdk.json

      cd /var/www/histudy/server
      sudo composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader
      sudo php artisan key:generate --force
      sudo php artisan migrate --force
      sudo php artisan optimize

      sudo chown -R www-data:www-data /var/www/histudy/server
      sudo chmod -R 775 /var/www/histudy/server/storage
      sudo chmod -R 775 /var/www/histudy/server/bootstrap/cache
