name: CI/CD Server Histudy

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Ensure server directory exists
        run: mkdir -p ./server

      - name: Create .env file
        run: |
          echo "LARAVEL_ENV=${{ secrets.LARAVEL_ENV }}" > .env

      - name: Debug secret
        run: echo "LARAVEL_ENV=${{ secrets.LARAVEL_ENV }}"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Laravel key
        run: php artisan key:generate --force

      - name: Set storage permissions
        run: |
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS EC2
        run: |
          ssh ${{ secrets.EC2_HOST }} "cd /var/www/html && git pull && composer install --no-dev && php artisan migrate --force && php artisan optimize"
