name: CI/CD server Histudy

on:
  workflow_call: # Để nhận workflow gọi từ workflow cha

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Ensure server directory exists
        run: mkdir -p ./server

      - name: Create .env file
        run: |
          echo "LARAVEL_ENV=${{ secrets.LARAVEL_ENV }}" > .env  # Truyền trực tiếp giá trị từ secrets

      - name: Debug secret
        run: echo "LARAVEL_ENV=${{ secrets.LARAVEL_ENV }}" # Kiểm tra giá trị LARAVEL_ENV

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Laravel key
        run: php artisan key:generate --force

      - name: Set storage permissions
        run: |
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

      # - name: Prepare EC2 server directory
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p /var/www/html/histudy-server"

      # - name: Deploy to EC2
      #   run: |
      #     scp -i ${{ secrets.EC2_PRIVATE_KEY }} -r . ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/histudy-server
      #     ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /var/www/html/histudy-server && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan storage:link"
