name: CI/CD Server Histudy

on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
  LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }}

jobs:
  deploy:
    runs-on: self-hosted # Sử dụng runner tự host của bạn

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            # Kiểm tra xem thư mục server có tồn tại không, nếu không thì tạo
            if [ ! -d "/var/www/histudy/server" ]; then
              echo "Directory /var/www/histudy/server does not exist. Creating it now."
              sudo mkdir -p /var/www/histudy/server
              sudo chown ubuntu:ubuntu /var/www/histudy/server
              sudo chmod -R 775 /var/www/histudy/server
            else
              echo "Directory /var/www/histudy/server already exists."
            fi

            # Sao chép mã nguồn từ actions runner lên EC2
            echo "Copying code to /var/www/histudy/server"
            sudo cp -r /home/actions-runner/work/histudy/histudy/* /var/www/histudy/server/

            # Tạo file .env và sao chép nội dung từ LARAVEL_ENV vào
            echo "LARAVEL_ENV=${{ env.LARAVEL_ENV }}" | sudo tee /var/www/histudy/server/.env

            # Di chuyển vào thư mục chứa server
            cd /var/www/histudy/server

            # Cài đặt dependencies cho Laravel
            sudo composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

            # Tạo key cho Laravel
            sudo php artisan key:generate --force

            # Chạy migrate và optimize
            sudo php artisan migrate --force
            sudo php artisan optimize

            # Cấp quyền cho thư mục storage và bootstrap/cache
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache
