name: Deploy server Histudy to EC2

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Copy .env file from secrets
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Laravel key
        run: php artisan key:generate --force

      - name: Set storage permissions
        run: |
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

      - name: Prepare EC2 server directory
        run: |
          ssh -i "$SSH_PRIVATE_KEY" ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} "mkdir -p /var/www/html/histudy-server"

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          scp -i "$SSH_PRIVATE_KEY" -r . ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }}:/var/www/html/histudy-server
          ssh -i "$SSH_PRIVATE_KEY" ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} "cd /var/www/html/histudy-server && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan storage:link"
